import os

import requests
import pytest
from dotenv import load_dotenv

# here we load all env variables from local .env file
# in CI pipeline we sync our ci env variables to Github secrets/variables
load_dotenv()

PROMETHEUS_URL = os.environ.get("PROMETHEUS_URL")

@pytest.fixture(scope="session")
def prometheus_url():
    return PROMETHEUS_URL


@pytest.fixture(scope="session")
def query_prometheus():
    def _query(query: str):
        r = requests.get(f"{PROMETHEUS_URL}/api/v1/query", params={"query": query})
        r.raise_for_status()
        return r.json()

    return _query


@pytest.fixture(scope="session")
def query_range_prometheus():
    def _query_range(query: str, start: str, end: str, step: str = "30s"):
        r = requests.get(f"{PROMETHEUS_URL}/api/v1/query_range",
                         params={"query": query, "start": start, "end": end, "step": step})
        r.raise_for_status()
        return r.json()

    return _query_range


# --- for rule test cases ---
from pathlib import Path
from datetime import datetime
import time

PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT",
                                   os.environ.get("GITHUB_WORKSPACE", Path(__file__).parents[4])))
PROM_RULE_DIR = PROJECT_ROOT / "AutoTest-in-Action/pytest-in-action/configs/prometheus/rules/generated"
PROM_RELOAD_URL = f"{PROMETHEUS_URL}/-/reload"
PROM_RULES_API = f"{PROMETHEUS_URL}/api/v1/rules"


def _reload_prometheus():
    resp = requests.post(PROM_RELOAD_URL)
    assert resp.status_code == 200


def _timestamp():
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")


@pytest.fixture(scope="class")
def prometheus_rule_context(request):
    """
    Class-level fixture:
    - Generate rule file(s)
    - Reload Prometheus
    - Yield to tests
    - Cleanup + reload
    """
    PROM_RULE_DIR.mkdir(parents=True, exist_ok=True)
    test_name = request.node.name
    ts = _timestamp()
    rule_file = PROM_RULE_DIR / f"{test_name}__{ts}.yml"
    rule_content = f"""
groups:
- name: {test_name}_group
  rules:
  - record: test_pg_connections_{ts}
    expr: pg_stat_activity_count
  - alert: TestPostgresConnectionsHigh_{ts}
    expr: pg_stat_activity_count > 0
    for: 5s
    labels:
      severity: test
    annotations:
      summary: "Test alert generated by {test_name}"
"""
    rule_file.write_text(rule_content)
    _reload_prometheus()
    time.sleep(2)

    yield {
        "rule_file": rule_file,
        "timestamp": ts,
        "test_name": test_name
    }

    # cleanup
    rule_file.unlink(missing_ok=True)
    _reload_prometheus()
